// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6zQHT6mKiBWDELaUJ7Fy0Cu0Sk4iWTm4',
    appId: '1:337020828325:web:f6b7c851474224dedfab4c',
    messagingSenderId: '337020828325',
    projectId: 'crudmasterclass',
    authDomain: 'crudmasterclass.firebaseapp.com',
    storageBucket: 'crudmasterclass.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpc7B0XfFf-UF8-j9s3E-4QvSv7LAQzg',
    appId: '1:337020828325:android:e6316e645629a2badfab4c',
    messagingSenderId: '337020828325',
    projectId: 'crudmasterclass',
    storageBucket: 'crudmasterclass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLsc6j8G8AA6Lf9kaZApBhs0MoGrszbfE',
    appId: '1:337020828325:ios:3433d8a921e0e7fcdfab4c',
    messagingSenderId: '337020828325',
    projectId: 'crudmasterclass',
    storageBucket: 'crudmasterclass.appspot.com',
    iosBundleId: 'com.example.crudMasterclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLsc6j8G8AA6Lf9kaZApBhs0MoGrszbfE',
    appId: '1:337020828325:ios:3b76874d32b3e556dfab4c',
    messagingSenderId: '337020828325',
    projectId: 'crudmasterclass',
    storageBucket: 'crudmasterclass.appspot.com',
    iosBundleId: 'com.example.crudMasterclass.RunnerTests',
  );
}
